version:  '3'
services:
    sonarqube:
        container_name:  sonarqube
        image:  sonarqube:latest
        platform: linux/amd64
        ports:
            -  "9000:9000"
            -  "9092:9092"