version:  '3'
services:
    sonarqube:
        container_name:  sonarqube
        image:  sonarqube:latest
        expose: 
            - "9000"
        ports:
            -  "9000:9000"
            -  "9092:9092"